# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_meandB <- function(x, windowSize) {
    .Call(`_RcppRollMeandB_roll_meandB`, x, windowSize)
}

roll_meandB_threshold <- function(x, windowRowSize, windowColSize, threshold) {
    .Call(`_RcppRollMeandB_roll_meandB_threshold`, x, windowRowSize, windowColSize, threshold)
}

roll_meandB_vector <- function(x, windowSize) {
    .Call(`_RcppRollMeandB_roll_meandB_vector`, x, windowSize)
}

